---
platform: linux
image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

inputs:
  - name: pipelines-repo
outputs:
  - name: om-installation

run:
  path: pipelines-repo/tasks/export-om-installation/task.sh

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
