resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))

- name: pcf-ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((opsman_major_minor_version))
    sort_by: semver

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit


groups:
- name: om
  jobs:
  - deploy-opsman
  - configure-director
  - deploy-director
- name: post-deploy
  jobs:
  - 
- name: cleanup
  jobs:
  - wipe-env


jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-opsman-product
      resource: pcf-ops-manager
      params: {globs: ["*.ova"]}
      trigger: true

  - task: deploy
    file: pipelines-repo/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((om_data_store))
      GOVC_NETWORK: ((om_vm_network))
      GOVC_RESOURCE_POOL: ((om_resource_pool))
      GOVC_HOST: ((om_vm_host))
      OPS_MGR_HOST: ((ops_mgr_host))
      OM_VM_FOLDER: ((om_vm_folder))
      OPS_MGR_SSH_PWD: ((om_ssh_pwd))
      OM_NTP_SERVERS: ((om_ntp_servers))
      OM_DNS_SERVERS: ((om_dns_servers))
      OM_GATEWAY: ((om_gateway))
      OM_NETMASK: ((om_netmask))
      OM_IP: ((om_ip))
      OM_VM_NETWORK: ((om_vm_network))
      OM_VM_NAME: ((om_vm_name))
      OM_RESOURCE_POOL: ((om_resource_pool))
      OPSMAN_DISK_TYPE: ((opsman_disk_type))
      OM_VM_POWER_STATE: ((om_vm_power_state))

- name: configure-director
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-opsman]
      trigger: true

  - task: config-opsman-auth
    file: pipelines-repo/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      OM_DECRYPTION_PWD: ((om_decryption_pwd))

  - task: configure-director
    file: pipelines-repo/tasks/config-opsdir-pas-nsxt/task.yml
    params:
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      VCENTER_HOST: ((vcenter_host))
      VCENTER_USR: ((vcenter_usr))
      VCENTER_PWD: ((vcenter_pwd))
      VCENTER_DATA_CENTER: ((vcenter_data_center))
      VCENTER_DISK_TYPE: ((vm_disk_type))
      EPHEMERAL_STORAGE_NAMES: ((ephemeral_storage_names))
      PERSISTENT_STORAGE_NAMES: ((persistent_storage_names))
      BOSH_VM_FOLDER:  ((bosh_vm_folder))
      BOSH_TEMPLATE_FOLDER: ((bosh_template_folder))
      BOSH_DISK_PATH: ((bosh_disk_path))
      NSX_NETWORKING_ENABLED: ((nsx_networking_enabled))
      NSX_MODE: ((nsx_mode))
      NSX_ADDRESS: ((nsx_address))
      NSX_USERNAME: ((nsx_username))
      NSX_PASSWORD: ((nsx_password))
      NSX_CA_CERTIFICATE: ((nsx_ca_certificate))
      SSL_VERIFICATION_ENABLED: ((ssl_verification_enabled))
      NTP_SERVERS: ((ntp_servers))
      ENABLE_VM_RESURRECTOR: ((enable_vm_resurrector))
      METRICS_IP: ((metrics_ip))
      OPENTSDB_IP: ((opentsdb_ip))
      POST_DEPLOY_ENABLED: ((post_deploy_enabled))
      BOSH_RECREATE_ON_NEXT_DEPLOY: ((bosh_recreate_on_next_deploy))
      RETRY_BOSH_DEPLOYS: ((retry_bosh_deploys))
      KEEP_UNREACHABLE_VMS: ((keep_unreachable_vms))
      MAX_THREADS: ((max_threads))
      DIRECTOR_WORKER_COUNT: ((director_worker_count))
      OPS_DIR_HOSTNAME: ((ops_dir_hostname))
      PAGER_DUTY_ENABLED: ((pager_duty_enabled))
      PAGER_DUTY_SERVICE_KEY: ((pager_duty_service_key))
      PAGER_DUTY_HTTP_PROXY: ((pager_duty_http_proxy))
      HM_EMAIL_ENABLED: ((hm_email_enabled))
      SMTP_HOST: ((smtp_host))
      SMTP_PORT: ((smtp_port))
      SMTP_DOMAIN: ((smtp_domain))
      FROM_ADDRESS: ((from_address))
      RECIPIENTS_ADDRESS: ((recipients_address))
      SMTP_USER: ((smtp_user))
      SMTP_PASSWORD: ((smtp_password))
      SMTP_TLS_ENABLED: ((smtp_tls_enabled))
      BLOBSTORE_TYPE: ((blobstore_type))
      DATABASE_TYPE: ((database_type))
      EXTERNAL_MYSQL_DB_HOST: ((external_mysql_db_host))
      EXTERNAL_MYSQL_DB_PORT: ((external_mysql_db_port))
      EXTERNAL_MYSQL_DB_USER: ((external_mysql_db_user))
      EXTERNAL_MYSQL_DB_PASSWORD: ((external_mysql_db_password))
      EXTERNAL_MYSQL_DB_DATABASE: ((external_mysql_db_database))
      SYSLOG_ENABLED: ((syslog_enabled))
      SYSLOG_ADDRESS: ((syslog_address))
      SYSLOG_PORT: ((syslog_port))
      SYSLOG_TRANSPORT_PROTOCOL: ((syslog_transport_protocol))
      SYSLOG_TLS_ENABLED: ((syslog_tls_enabled))
      SYSLOG_PERMITTED_PEER: ((syslog_permitted_peer))
      SYSLOG_SSL_CA_CERTIFICATE: ((syslog_ssl_ca_certificate))
      ICMP_CHECKS_ENABLED: ((icmp_checks_enabled))
      INFRA_NETWORK_NAME: ((infra_network_name))
      INFRA_VCENTER_NETWORK: ((infra_vsphere_network))
      INFRA_NW_CIDR: ((infra_nw_cidr))
      INFRA_EXCLUDED_RANGE: ((infra_excluded_range))
      INFRA_NW_DNS: ((infra_nw_dns))
      INFRA_NW_GATEWAY: ((infra_nw_gateway))
      INFRA_NW_AZS: ((infra_nw_azs))
      DEPLOYMENT_NETWORK_NAME: ((deployment_network_name))
      DEPLOYMENT_VCENTER_NETWORK: ((deployment_vsphere_network))
      DEPLOYMENT_NW_CIDR: ((deployment_nw_cidr))
      DEPLOYMENT_EXCLUDED_RANGE: ((deployment_excluded_range))
      DEPLOYMENT_NW_DNS: ((deployment_nw_dns))
      DEPLOYMENT_NW_GATEWAY: ((deployment_nw_gateway))
      DEPLOYMENT_NW_AZS: ((deployment_nw_azs))
      SERVICES_NETWORK_NAME: ((services_network_name))
      SERVICES_VCENTER_NETWORK: ((services_vsphere_network))
      SERVICES_NW_CIDR: ((services_nw_cidr))
      SERVICES_EXCLUDED_RANGE: ((services_excluded_range))
      SERVICES_NW_DNS: ((services_nw_dns))
      SERVICES_NW_GATEWAY: ((services_nw_gateway))
      SERVICES_NW_AZS: ((services_nw_azs))
      AZ_1: ((az_1_name))
      AZ_1_CLUSTER_NAME: ((az_1_cluster_name))
      AZ_1_RP_NAME: ((az_1_rp_name))
      AZ_2: ((az_2_name))
      AZ_2_CLUSTER_NAME: ((az_2_cluster_name))
      AZ_2_RP_NAME: ((az_2_rp_name))
      AZ_3: ((az_3_name))
      AZ_3_CLUSTER_NAME: ((az_3_cluster_name))
      AZ_3_RP_NAME: ((az_3_rp_name))
      TRUSTED_CERTIFICATES: ((trusted_certificates))
      GENERATE_VM_PASSWORDS: ((generate_vm_passwords))

- name: deploy-director
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-director]
      trigger: true

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))

- name: wipe-env
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: false
  - task: wipe
    file: pipelines-repo/tasks/wipe-env/task.yml
    params:
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      OPSMAN_IP: ((om_ip))
      GOVC_INSECURE: ((vcenter_insecure))
      GOVC_CA_CERT: ((vcenter_ca_cert))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((om_data_store))
      GOVC_NETWORK: ((om_vm_network))
      GOVC_RESOURCE_POOL: ((om_resource_pool))
      GOVC_HOST: ((om_vm_host))
