---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:

inputs:
  - name: pivnet-product
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/upload-product/task.sh
