---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PRODUCT_IDENTIFIER:
  ERRANDS:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/disable-errands/task.sh
