---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

params:
  IAAS:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  ERT_SINGLETON_JOB_AZ:
  DEPLOYMENT_NW_AZS:
  NETWORK_NAME:
  ENABLE_SECURITY_EVENT_LOGGING:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_DRAIN_BUFFER_SIZE:
  COMPANY_NAME:
  AUTHENTICATION_MODE:
  LOGGREGATOR_ENDPOINT_PORT:
  SSL_CERT:
  SSL_PRIVATE_KEY:
  SAML_SSL_CERT:
  SAML_SSL_PRIVATE_KEY:
  HAPROXY_FORWARD_TLS:
  HAPROXY_BACKEND_CA:
  ROUTER_TLS_CIPHERS:
  HAPROXY_TLS_CIPHERS:
  DISABLE_HTTP_PROXY:
  TCP_ROUTING:
  TCP_ROUTING_PORTS:
  ROUTE_SERVICES:
  IGNORE_SSL_CERT:
  SECURITY_ACKNOWLEDGEMENT:
  SMTP_FROM:
  SMTP_ADDRESS:
  SMTP_PORT:
  SMTP_USER:
  SMTP_PWD:
  SMTP_AUTH_MECHANISM:
  LDAP_URL:
  LDAP_USER:
  LDAP_PWD:
  SEARCH_BASE:
  SEARCH_FILTER:
  GROUP_SEARCH_BASE:
  GROUP_SEARCH_FILTER:
  MAIL_ATTR_NAME:
  FIRST_NAME_ATTR:
  LAST_NAME_ATTR:
  SYSTEM_DOMAIN:
  APPS_DOMAIN:
  DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB:
  DEFAULT_QUOTA_MAX_SERVICES_COUNT:
  HA_PROXY_IPS:
  SKIP_CERT_VERIFY:
  DISABLE_INSECURE_COOKIES:
  ROUTER_STATIC_IPS:
  MYSQL_PROXY_STATIC_IPS:
  MYSQL_PROXY_SERVICE_HOSTNAME:
  MYSQL_PROXY_STARTUP_DELAY:
  MYSQL_PROXY_SHUTDOWN_DELAY:
  ROUTER_REQUEST_TIMEOUT_IN_SEC:
  GARDEN_NETWORK_POOL_CIDR:
  GARDEN_NETWORK_MTU:
  MYSQL_MONITOR_EMAIL:
  MYSQL_BACKUPS:
  MYSQL_BACKUPS_SCP_SERVER:
  MYSQL_BACKUPS_SCP_PORT:
  MYSQL_BACKUPS_SCP_USER:
  MYSQL_BACKUPS_SCP_KEY:
  MYSQL_BACKUPS_SCP_DESTINATION:
  MYSQL_BACKUPS_SCP_CRON_SCHEDULE:
  MYSQL_BACKUPS_S3_ENDPOINT_URL:
  MYSQL_BACKUPS_S3_BUCKET_NAME:
  MYSQL_BACKUPS_S3_BUCKET_PATH:
  MYSQL_BACKUPS_S3_ACCESS_KEY_ID:
  MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY:
  MYSQL_BACKUPS_S3_CRON_SCHEDULE:
  ALLOW_APP_SSH_ACCESS:
  TCP_ROUTER_STATIC_IPS:
  SSH_STATIC_IPS:
  CONSUL_SERVER_INSTANCES:
  NATS_INSTANCES:
  NFS_SERVER_INSTANCES:
  MYSQL_PROXY_INSTANCES:
  MYSQL_INSTANCES:
  BACKUP_PREPARE_INSTANCES:
  UAA_INSTANCES:
  CLOUD_CONTROLLER_INSTANCES:
  HA_PROXY_INSTANCES:
  HA_PROXY_LB_NAME:
  HAPROXY_FLOATING_IPS:
  ROUTER_INSTANCES:
  MYSQL_MONITOR_INSTANCES:
  CLOCK_GLOBAL_INSTANCES:
  CLOUD_CONTROLLER_WORKER_INSTANCES:
  DIEGO_DATABASE_INSTANCES:
  DIEGO_BRAIN_INSTANCES:
  DIEGO_CELL_INSTANCES:
  DOPPLER_INSTANCES:
  LOGGREGATOR_TC_INSTANCES:
  TCP_ROUTER_INSTANCES:
  SYSLOG_ADAPTER_INSTANCES:
  INTERNET_CONNECTED:
  CONTAINER_NETWORKING_NW_CIDR:
  TCP_ROUTER_NSX_SECURITY_GROUP:
  TCP_ROUTER_NSX_LB_EDGE_NAME:
  TCP_ROUTER_NSX_LB_POOL_NAME:
  TCP_ROUTER_NSX_LB_SECURITY_GROUP:
  TCP_ROUTER_NSX_LB_PORT:
  ROUTER_NSX_SECURITY_GROUP:
  ROUTER_NSX_LB_EDGE_NAME:
  ROUTER_NSX_LB_POOL_NAME:
  ROUTER_NSX_LB_SECURITY_GROUP:
  ROUTER_NSX_LB_PORT:
  DIEGO_BRAIN_NSX_SECURITY_GROUP:
  DIEGO_BRAIN_NSX_LB_EDGE_NAME:
  DIEGO_BRAIN_NSX_LB_POOL_NAME:
  DIEGO_BRAIN_NSX_LB_SECURITY_GROUP:
  DIEGO_BRAIN_NSX_LB_PORT:
  CONTAINER_NETWORKING_INTERFACE_PLUGIN:
  CREDHUB_PASSWORD:
  BLOBSTORE_INTERNAL_ACCESS_SUBNET:
  ENABLE_GROOTFS:
  ROUTING_TLS_TERMINATION:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-ert-2.0/task.sh
