resource_types: []

resources:
- name: czero-cflinuxfs2
  type: docker-image
  source:
    repository: czero/rootfs
    tag: latest
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    
- name: czero-cflinuxfs2-harbor
  type: docker-image
  source:
    repository: harbor.lab13.cse.lab:443/library/czero-rootfs
    tag: latest
    username: {{harbor_username}}
    password: {{harbor_password}}
    insecure_registries: 
    - harbor.lab13.cse.lab:443

- name: pcfnorm-rootfs
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: latest
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    
- name: pcfnorm-rootfs-harbor
  type: docker-image
  source:
    repository: harbor.lab13.cse.lab:443/library/pcfnorm-rootfs
    tag: latest
    username: {{harbor_username}}
    password: {{harbor_password}}
    insecure_registries: 
    - harbor.lab13.cse.lab:443    
    
    
jobs:
- name: czero-rootfs
  plan:
  - get: czero-cflinuxfs2
    trigger: true
    params:
      save: true
      rootfs: false
  - put: czero-cflinuxfs2-harbor
    params: 
      #import_file: czero-cflinuxfs2/image
      load: czero-cflinuxfs2
      tag: czero-cflinuxfs2/tag
      
- name: pcfnorm-rootfs
  plan:
  - get: pcfnorm-rootfs
    trigger: true
    params:
      save: true
      rootfs: false
  - put: pcfnorm-rootfs-harbor
    params: 
      #import_file: czero-cflinuxfs2/image
      load: pcfnorm-rootfs
      tag: pcfnorm-rootfs/tag