# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cf_api_params: &cf_api_params
  CF_API_URI: {{cf_api_uri}}
  CF_USERNAME: {{cf_user}}
  CF_PASSWORD: {{cf_password}}


resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))

- name: custom-task-image
  type: registry-image
  source:
    repository: ((registry_endpoint))/((registry_repo_customtask))
    #username: ((registry_username))
    #password: ((registry_password))
    tag: 'latest'
    insecure: true
    # ca_certs:
    # - ((registry_ca_cert))

- name: binary-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: binary-buildpack
    #product_version: Binary*

- name: dotnet-core-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: dotnet-core-buildpack
    #product_version: .NET*

- name: go-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: go-buildpack
    #product_version: Go*

- name: java-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: java-buildpack
    #product_version: Java Buildpack (offline)*

- name: nodejs-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: nodejs-buildpack
    product_version: 1\.8\* #NodeJS*

- name: php-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: php-buildpack
    #product_version: PHP*

- name: python-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: python-buildpack
    #product_version: Python*

- name: ruby-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ruby-buildpack
    #product_version: Ruby*

- name: staticfile-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: staticfile-buildpack
    #product_version: Staticfile*

- name: tc-buildpack
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: tc-server-buildpack
    #product_version: "tc Server*"

# - name: schedule
#   type: time
#   source:
#     interval: 30m
#     start: "12:00 AM"
#     stop: "2:00 AM"
#     location: America/Chicago
#     days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

# - name: schedule
#   type: time
#   source:
#     start: {{schedule_start}}
#     stop: {{schedule_stop}}
#     location: {{schedule_location}}
#     days: [{{schedule_days}}]
#     initial_version: true

jobs:
- name: regulator
  plan:
  # - get: schedule
  #   trigger: true
  - get: binary-buildpack
    params: { globs: [] }
  - get: dotnet-core-buildpack
    params: { globs: [] }
  - get: go-buildpack
    params: { globs: [] }
  - get: java-buildpack
    params: { globs: [] }
  - get: nodejs-buildpack
    params: { globs: [] }
  - get: php-buildpack
    params: { globs: [] }
  - get: python-buildpack
    params: { globs: [] }
  - get: ruby-buildpack
    params: { globs: [] }
  - get: staticfile-buildpack
    params: { globs: [] }
  - get: tc-buildpack
    params: { globs: [] }

- name: stage-binary-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    resource: binary-buildpack
    trigger: true
    passed: [regulator]

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: binary_buildpack_latest

- name: promote-binary-buildpack
  serial_groups: [cc-api]
  plan:
  - get: binary-buildpack
    trigger: true
    passed: [stage-binary-buildpack]
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: binary_buildpack_latest
      TARGET_BUILDPACK_NAME: binary_buildpack

- name: stage-dotnet-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    resource: dotnet-core-buildpack
    passed: [regulator]
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: dotnet_core_buildpack_offline_latest

- name: promote-dotnet-buildpack
  serial_groups: [cc-api]
  plan:
  - get: dotnet-core-buildpack
    trigger: true
    passed: [stage-dotnet-buildpack]
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: dotnet_core_buildpack_offline_latest
      TARGET_BUILDPACK_NAME: dotnet_core_buildpack_offline

- name: stage-go-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    resource: go-buildpack
    passed: [regulator]
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: go_buildpack_latest

- name: promote-go-buildpack
  serial_groups: [cc-api]
  plan:
  - get: go-buildpack
    passed: [stage-go-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: go_buildpack_latest
      TARGET_BUILDPACK_NAME: go_buildpack

- name: stage-java-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: java-buildpack
    trigger: true
    params:
      globs:
      - "*offline*"

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: java_buildpack_offline_latest

- name: promote-java-buildpack
  serial_groups: [cc-api]
  plan:
  - get: java-buildpack
    passed: [stage-java-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: java_buildpack_offline_latest
      TARGET_BUILDPACK_NAME: java_buildpack_offline

- name: stage-nodejs-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: nodejs-buildpack
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: nodejs_buildpack_latest

- name: promote-nodejs-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: nodejs-buildpack
    passed: [stage-nodejs-buildpack]
    trigger: true
    params: {globs: []}
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: nodejs_buildpack_latest
      TARGET_BUILDPACK_NAME: nodejs_buildpack

- name: stage-php-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: php-buildpack
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: php_buildpack_latest

- name: promote-php-buildpack
  serial_groups: [cc-api]
  plan:
  - get: php-buildpack
    passed: [stage-php-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: php_buildpack_latest
      TARGET_BUILDPACK_NAME: php_buildpack

- name: stage-python-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: python-buildpack
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: python_buildpack_latest

- name: promote-python-buildpack
  serial_groups: [cc-api]
  plan:
  - get: python-buildpack
    passed: [stage-python-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: python_buildpack_latest
      TARGET_BUILDPACK_NAME: python_buildpack

- name: stage-ruby-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: ruby-buildpack
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: ruby_buildpack_latest

- name: promote-ruby-buildpack
  serial_groups: [cc-api]
  plan:
  - get: ruby-buildpack
    passed: [stage-ruby-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: ruby_buildpack_latest
      TARGET_BUILDPACK_NAME: ruby_buildpack

- name: stage-staticfile-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: staticfile-buildpack
    trigger: true

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: staticfile_buildpack_latest

- name: promote-staticfile-buildpack
  serial_groups: [cc-api]
  plan:
  - get: staticfile-buildpack
    passed: [stage-staticfile-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image
  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: staticfile_buildpack_latest
      TARGET_BUILDPACK_NAME: staticfile_buildpack

- name: stage-tcserver-buildpack
  serial_groups: [cc-api]
  plan:
  - get: pipelines-repo
  - get: custom-task-image
  - get: buildpack
    passed: [regulator]
    resource: tc-buildpack
    trigger: true
    params:
      globs:
      - "*offline*"

  - task: stage
    image: custom-task-image
    file: pipelines-repo/tasks/stage-buildpack/task.yml
    params:
      <<: *cf_api_params
      BUILDPACK_NAME: tc_buildpack_latest

- name: promote-tcserver-buildpack
  serial_groups: [cc-api]
  plan:
  - get: tc-buildpack
    passed: [stage-tcserver-buildpack]
    trigger: true
    params: {globs: []}
  - get: pipelines-repo
  - get: custom-task-image

  - task: promote
    image: custom-task-image
    file: pipelines-repo/tasks/promote-buildpack/task.yml
    params:
      <<: *cf_api_params
      SOURCE_BUILDPACK_NAME: tc_buildpack_latest
      TARGET_BUILDPACK_NAME: tc_buildpack

