---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}


params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  AUTH_MODE:
  HARBOR_HOSTNAME:
  HARBOR_DOMAIN:
  HARBOR_ADMIN_PASSWORD:
  HARBOR_USE_CLAIR:
  HARBOR_USE_NOTARY:
  HARBOR_REGISTRY_STORAGE:
  HARBOR_LDAP_AUTH_URL:
  HARBOR_LDAP_AUTH_VERIFY_CERT:
  HARBOR_LDAP_AUTH_SEARCHDB:
  HARBOR_LDAP_AUTH_SEARCHPWD:
  HARBOR_LDAP_AUTH_BASEDN:
  HARBOR_LDAP_AUTH_UID:
  HARBOR_LDAP_AUTH_FILTER:
  HARBOR_LDAP_AUTH_SCOPE:
  HARBOR_LDAP_AUTH_TIMEOUT:
  HARBOR_S3_REGISTRY_STORAGE_ACCESS_KEY:
  HARBOR_S3_REGISTRY_STORAGE_SECRET_KEY:
  HARBOR_S3_REGISTRY_STORAGE_REGION:
  HARBOR_S3_REGISTRY_STORAGE_ENDPOINT_URL:
  HARBOR_S3_REGISTRY_STORAGE_BUCKET:
  HARBOR_S3_REGISTRY_STORAGE_ROOT_DIRECTORY:
  HARBOR_CERT_PEM:
  HARBOR_PRIVATE_KEY_PEM:
  HARBOR_SERVER_CERT_CA_PEM: 


inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-harbor-container-registry/task.sh
