---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

inputs:
- name: pipelines-repo

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  TRUSTED_CERTIFICATES:


run:
  path: pipelines-repo/tasks/add-opsmgr-rootca-to-director/task.sh
