---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_NAME:
  DEPLOY_SERVICE_BROKER_BROKER_MAX_INSTANCES:
  DEPLOY_SERVICE_BROKER_BUILDPACK:
  DEPLOY_SERVICE_BROKER_DISABLE_CERT_CHECK:
  DEPLOY_SERVICE_BROKER_INSTANCES_APP_PUSH_TIMEOUT:
  DEPLOY_SERVICE_BROKER_MESSAGE_BUS_SERVICE:
  DEPLOY_SERVICE_BROKER_MESSAGE_BUS_SERVICE_PLAN:
  DEPLOY_SERVICE_BROKER_PERSISTENCE_STORE_SERVICE:
  DEPLOY_SERVICE_BROKER_PERSISTENCE_STORE_SERVICE_PLAN:
  DEPLOY_SERVICE_BROKER_SECURE_CREDENTIALS:
  REGISTER_SERVICE_BROKER_ENABLE_GLOBAL_ACCESS:

inputs:
  - name: pipelines-repo
  - name: om-cli
  - name: jq

run:
  path: pipelines-repo/tasks/config-spring-cloud-services/task.sh
