---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pipelines-repo

run:
  path: pipelines-repo/tasks/deploy-pks-test-app/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
  YAML_SOURCE:
  VALUE_TO_REPLACE:
  REPLACEMENT_VALUE:
  UAA_URL:
