---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
  - name: pipelines-repo

outputs:
  - name: diagnostic-report

params:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_HOST:

run:
  path: pipelines-repo/tasks/export-opsmgr-diagnostic-report/task.sh
