resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))

- name: pivotal-container-service
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/PKS/pivotal-container-service-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true

- name: harbor-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/Tiles/harbor-container-registry-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true


jobs:
- name: upload-pks
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: false
    - get: pivnet-product
      resource: pivotal-container-service
      params: {globs: ["*.pivotal"]}
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-pks
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-pks
  plan:
  - aggregate:
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-pks]
      trigger: false
    - get: pivnet-product
      resource: pivotal-container-service
      params: {globs: ["*.pivotal"]}
      passed: [upload-pks]
    - get: pipelines-repo


  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      PRODUCT_IDENTIFIER: pivotal-container-service

- name: stage-pks
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-pks]
      trigger: false



  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: pivotal-container-service

- name: upload-harbor
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: harbor-s3
      params: {globs: ["*.pivotal"]}
      trigger: false
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-harbor
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

- name: upload-stemcell-harbor
  plan:
  - aggregate:
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
      passed: [upload-harbor]
      trigger: false
    - get: pivnet-product
      resource: harbor-s3
      params: {globs: ["*.pivotal"]}
      passed: [upload-harbor]
    - get: pipelines-repo



  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))
      PRODUCT_IDENTIFIER: harbor-container-registry

- name: stage-harbor
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [upload-stemcell-harbor]
      trigger: false


  - task: stage-tile
    file: pipelines-repo/tasks/stage-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PRODUCT_IDENTIFIER: harbor-container-registry

- name: apply-changes
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: false
      passed: [stage-pks, stage-harbor]

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
