resource_types:


resources:
- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))
jobs:

- name: deploy-app
  plan:
  - aggregate:
    - get: pipelines-repo
      trigger: false


  - task: deploy-pks-app
    file: pipelines-repo/tasks/deploy-pks-app/task.yml
    params:
      UAA_URL: ((uaa_url))
      PKS_CLI_USERNAME: ((pks_cli_username))
      PKS_CLI_PASSWORD: ((pks_cli_password))
      K8S_NAMESPACE: ((k8s_namespace))
      APP_YAML_URL: ((app_yaml_url))
      VALUE_TO_REPLACE: ((yaml_value_to_replace))
      REPLACEMENT_VALUE: ((yaml_replacement_value))
      K8S_CLUSTERNAME: ((k8s_clustername))
      K8S_NAMESPACE: ((k8s_namespace))
