---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  HEALTHWATCH_FORWARDER_BOSHHEALTH_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_BOSHTASKS_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_CANARY_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_CLI_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_FOUNDATION_NAME:
  HEALTHWATCH_FORWARDER_HEALTH_CHECK_AZ:
  HEALTHWATCH_FORWARDER_HEALTH_CHECK_VM_TYPE:
  HEALTHWATCH_FORWARDER_INGESTOR_INSTANCE_COUNT:
  HEALTHWATCH_FORWARDER_OPSMAN_INSTANCE_COUNT:
  HEALTHWATCH_MYSQL_SKIP_NAME_RESOLVE:
  HEALTHWATCH_OPSMAN:
  HEALTHWATCH_OPSMAN_ENABLE_URL:
  HEALTHWATCH_MYSQL_PERSISTENT_DISK_MB:
  HEALTHWATCH_MYSQL_INSTANCES:
  HEALTHWATCH_MYSQL_INSTANCE_TYPE:
  HEALTHWATCH_REDIS_INSTANCES:
  HEALTHWATCH_REDIS_INSTANCE_TYPE:
  HEALTHWATCH_FORWARDER_PERSISTENT_DISK_MB:
  HEALTHWATCH_FORWARDER_INSTANCES:
  HEALTHWATCH_FORWARDER_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-p-healthwatch/task.sh
