---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PRODUCT_NAME:
  CF_MYSQL_BROKER_ALLOW_TABLE_LOCKS:
  CF_MYSQL_BROKER_BIND_HOSTNAME:
  CF_MYSQL_BROKER_QUOTA_ENFORCER_PAUSE:
  MYSQL_ALLOW_LOCAL_INFILE:
  MYSQL_ALLOW_REMOTE_ADMIN_ACCESS:
  MYSQL_BINLOG_EXPIRE_DAYS:
  MYSQL_CLI_HISTORY:
  MYSQL_CLUSTER_NAME:
  MYSQL_CLUSTER_PROBE_TIMEOUT:
  MYSQL_INNODB_LARGE_PREFIX_ENABLED:
  MYSQL_INNODB_STRICT_MODE:
  MYSQL_MAX_CONNECTIONS:
  MYSQL_METRICS_POLLING_FREQUENCY:
  MYSQL_MYSQL_START_TIMEOUT:
  MYSQL_ROADMIN_PASSWORD:
  MYSQL_SKIP_NAME_RESOLVE:
  MYSQL_TABLE_DEFINITION_CACHE:
  MYSQL_TABLE_OPEN_CACHE:
  MYSQL_TMP_TABLE_SIZE:
  BACKUP_OPTIONS:
  BACKUP_OPTIONS_ENABLE_BACKUP_ALL_MASTERS:
  BACKUP_OPTIONS_ENABLE_CRON_SCHEDULE:
  BACKUPS:
  BACKUPS_AZURE_BASE_URL:
  BACKUPS_AZURE_CONTAINER:
  BACKUPS_AZURE_CONTAINER_PATH:
  BACKUPS_AZURE_STORAGE_ACCESS_KEY:
  BACKUPS_AZURE_STORAGE_ACCOUNT:
  BACKUPS_ENABLE_ACCESS_KEY_ID:
  BACKUPS_ENABLE_BUCKET_NAME:
  BACKUPS_ENABLE_BUCKET_PATH:
  BACKUPS_ENABLE_ENDPOINT_URL:
  BACKUPS_ENABLE_REGION:
  BACKUPS_ENABLE_SECRET_ACCESS_KEY:
  BACKUPS_GCS_BUCKET_NAME:
  BACKUPS_GCS_PROJECT_ID:
  BACKUPS_GCS_SERVICE_ACCOUNT_JSON:
  BACKUPS_SCP_DESTINATION:
  BACKUPS_SCP_PORT:
  BACKUPS_SCP_SCP_KEY:
  BACKUPS_SCP_SERVER:
  BACKUPS_SCP_USER:
  BUFFER_POOL_SIZE:
  BUFFER_POOL_SIZE_BYTES_BUFFER_POOL_SIZE_BYTES:
  BUFFER_POOL_SIZE_PERCENT_BUFFER_POOL_SIZE_PERCENT:
  INNODB_FLUSH_LOG_AT_TRX_COMMIT:
  OPTIONAL_PROTECTIONS:
  OPTIONAL_PROTECTIONS_ENABLE_CANARY_POLL_FREQUENCY:
  OPTIONAL_PROTECTIONS_ENABLE_CANARY_WRITE_READ_DELAY:
  OPTIONAL_PROTECTIONS_ENABLE_NOTIFY_ONLY:
  OPTIONAL_PROTECTIONS_ENABLE_PREVENT_AUTO_REJOIN:
  OPTIONAL_PROTECTIONS_ENABLE_RECIPIENT_EMAIL:
  OPTIONAL_PROTECTIONS_ENABLE_REPLICATION_CANARY:
  PLAN_COLLECTION:
  SERVER_ACTIVITY_LOGGING:
  SERVER_ACTIVITY_LOGGING_ENABLE_AUDIT_LOGGING_EVENTS:
  SERVER_ACTIVITY_LOGGING_ENABLE_SERVER_AUDIT_EXCLUDED_USERS_CSV:
  SYSLOG:
  SYSLOG_ENABLED_ADDRESS:
  SYSLOG_ENABLED_PORT:
  SYSLOG_ENABLED_PROTOCOL:
  PROXY_SHUTDOWN_DELAY:
  PROXY_STARTUP_DELAY:
  PROXY_STATIC_IPS:
  MYSQL_INSTANCES:
  MYSQL_INSTANCE_TYPE:
  MYSQL_PERSISTENT_DISK_MB:
  BACKUP_PREPARE_INSTANCES:
  BACKUP_PREPARE_INSTANCE_TYPE:
  BACKUP_PREPARE_PERSISTENT_DISK_MB:
  PROXY_INSTANCES:
  PROXY_INSTANCE_TYPE:
  MONITORING_INSTANCES:
  MONITORING_INSTANCE_TYPE:
  CF_MYSQL_BROKER_INSTANCES:
  CF_MYSQL_BROKER_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-mysql/task.sh
