---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pipelines-repo

outputs:
- name: out

run:
  path: pipelines-repo/tasks/dump-bosh-logs/task.sh

params:
  DEBUG: 
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  DIRECTOR_IP:
