---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICE_NETWORK_NAME:
  OTHER_AZS:
  SINGLETON_JOBS_AZ:
  PLAN_1_AZS:
  PLAN_2_AZS:
  PLAN_3_AZS:
  BACKUPS:
  BACKUPS_AZURE_BASE_URL:
  BACKUPS_AZURE_CONTAINER:
  BACKUPS_AZURE_CONTAINER_PATH:
  BACKUPS_AZURE_STORAGE_ACCESS_KEY:
  BACKUPS_AZURE_STORAGE_ACCOUNT:
  BACKUPS_S3_ACCESS_KEY_ID:
  BACKUPS_S3_BUCKET_NAME:
  BACKUPS_S3_BUCKET_PATH:
  BACKUPS_S3_ENDPOINT_URL:
  BACKUPS_S3_REGION:
  BACKUPS_S3_SECRET_ACCESS_KEY:
  BACKUPS_GCS_BUCKET_NAME:
  BACKUPS_GCS_PROJECT_ID:
  BACKUPS_GCS_SERVICE_ACCOUNT_JSON:
  BACKUPS_SCP_DESTINATION:
  BACKUPS_SCP_PORT:
  BACKUPS_SCP_SCP_KEY:
  BACKUPS_SCP_SERVER:
  BACKUPS_SCP_USER:
  SYSLOG:
  SYSLOG_ENABLED_ADDRESS:
  SYSLOG_ENABLED_PORT:
  SYSLOG_ENABLED_PROTOCOL:
  CF_MYSQL_BROKER_INSTANCES:
  CF_MYSQL_BROKER_INSTANCE_TYPE:

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-mysql-v2/task.sh
