---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
  - name: pipelines-repo
  - name: pivnet-cli

outputs:
  - name: out

params:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_HOST:
  PIVNET_API_TOKEN:

run:
  path: pipelines-repo/tasks/report-tile-versions/task.sh
