---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  OPS_MGR_HOST:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  VCENTER_HOST:
  VCENTER_USR:
  VCENTER_PWD:
  VCENTER_DATA_CENTER:
  VCENTER_DISK_TYPE:
  EPHEMERAL_STORAGE_NAMES:
  PERSISTENT_STORAGE_NAMES:
  BOSH_VM_FOLDER:
  BOSH_TEMPLATES_FOLDER:
  BOSH_DISK_PATH:
  NSX_NETWORKING_ENABLED:
  NSX_MODE:
  NSX_ADDRESS:
  NSX_PASSWORD:
  NSX_USERNAME:
  NSX_CA_CERTIFICATE:
  SSL_VERIFICATION_ENABLED:
  NTP_SERVERS:
  ENABLE_VM_RESURRECTOR:
  METRICS_IP:
  OPENTSDB_IP:
  POST_DEPLOY_ENABLED:
  BOSH_RECREATE_ON_NEXT_DEPLOY:
  RETRY_BOSH_DEPLOYS:
  KEEP_UNREACHABLE_VMS:
  MAX_THREADS:
  DIRECTOR_WORKER_COUNT:
  OPS_DIR_HOSTNAME:
  PAGER_DUTY_ENABLED:
  PAGER_DUTY_SERVICE_KEY:
  PAGER_DUTY_HTTP_PROXY:
  HM_EMAIL_ENABLED:
  SMTP_HOST:
  SMTP_PORT:
  SMTP_DOMAIN:
  FROM_ADDRESS:
  RECIPIENTS_ADDRESS:
  SMTP_USER:
  SMTP_PASSWORD:
  SMTP_TLS_ENABLED:
  BLOBSTORE_TYPE:
  DATABASE_TYPE:
  EXTERNAL_MYSQL_DB_HOST:
  EXTERNAL_MYSQL_DB_PORT:
  EXTERNAL_MYSQL_DB_USER:
  EXTERNAL_MYSQL_DB_PASSWORD:
  EXTERNAL_MYSQL_DB_DATABASE:
  SYSLOG_ENABLED:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  SYSLOG_TRANSPORT_PROTOCOL:
  SYSLOG_TLS_ENABLED:
  SYSLOG_PERMITTED_PEER:
  SYSLOG_SSL_CA_CERTIFICATE:
  ICMP_CHECKS_ENABLED:
  MGMT_NETWORK_NAME:
  MGMT_NW_IS_SERVICE_NW:
  MGMT_VCENTER_NETWORK:
  MGMT_NW_CIDR:
  MGMT_EXCLUDED_RANGE:
  MGMT_NW_DNS:
  MGMT_NW_GATEWAY:
  MGMT_NW_AZS:
  AZ_1:
  AZ_1_CLUSTER_NAME:
  AZ_1_RP_NAME:
  AZ_1_HOST_GROUP:
  AZ_2:
  AZ_2_CLUSTER_NAME:
  AZ_2_RP_NAME:
  AZ_2_HOST_GROUP:
  AZ_3:
  AZ_3_CLUSTER_NAME:
  AZ_3_RP_NAME:
  AZ_3_HOST_GROUP:
  TRUSTED_CERTIFICATES:
  GENERATE_VM_PASSWORDS:
  DIRECTOR_INSTANCE_TYPE:
  DIRECTOR_INSTANCES:
  DIRECTOR_PERSISTENT_DISK_SIZE_MB:
  COMPILATION_INSTANCE_TYPE:
  COMPILATION_INSTANCES:


inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-opsdir-pks-nsxt-multiaz/task.sh
