pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/BrianRagazzi/concourse-pipelines # [R] Pipelines github repo
github_branch: master

iaas_type: vsphere

debug: false # Set to true if you want to see all the tasks output. This will also show all the secrets and certs, so think twice

ert_major_minor_version: ^2\.1\..*$      # PCF Elastic Runtime minor version to track
nsxt_major_minor_version: ^2\.1\..*$   # NSX Container Plugin minor version to track

#schedule
#schedule_start: "4:00 AM" #"5:00 AM" or 0500 or 5AM
#schedule_stop: "5:00 AM" #"5:00 AM" or 0500 or 5AM
#schedule_location: "America/Chicago" #America/Chicago
#schedule_days: Friday  #Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr)) # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd)) # [R] Ops Manager admin password
