---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  DEBUG:
  PRODUCT_IDENTIFIER:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  SERVICES_NW_AZS:
  SERVICE_SINGLETON_JOB_AZ:
  ISOLATION_SEGMENT_DOMAINS:
  REPLICATOR_NAME:
  ENABLE_GROOTFS:
  GARDEN_DISK_CLEANUP:
  GOROUTER_SSL_CIPHERS:
  HAPROXY_FORWARD_TLS:
  BACKEND_CA:
  HAPROXY_MAX_BUFFER_SIZE:
  HAPROXY_SSL_CIPHERS:
  NETWORKING_POE_SSL_NAME:
  NETWORKING_POE_SSL_CERT_PEM:
  NETWORKING_POE_SSL_CERT_PRIVATE_KEY_PEM:
  NFS_VOLUME_DRIVER:
  LDAP_SERVER_HOST:
  LDAP_SERVER_PORT:
  LDAP_SERVICE_ACCOUNT_PASSWORD:
  LDAP_SERVICE_ACCOUNT_USER:
  LDAP_USER_FQDN:
  ROUTER_BACKEND_MAX_CONN:
  ROUTER_CLIENT_CERT_VALIDATION:
  ROUTING_CUSTOM_CA_CERTIFICATES:
  ROUTING_DISABLE_HTTP:
  ROUTING_MINIMUM_TLS_VERSION:
  ROUTING_TABLE_SHARDING_MODE:
  ROUTING_TLS_TERMINATION:
  SKIP_CERT_VERIFY:
  SYSTEM_LOGGING:
  SYSLOG_HOST:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:
  SYSLOG_RULE:
  SYSLOG_TLS_CA_CERT:
  SYSLOG_TLS_ENABLED:
  SYSLOG_TLS_PERMITTED_PEER:
  SYSLOG_USE_TCP_FOR_FILE_FORWARDING_LOCAL_TRANSPORT:
  HA_PROXY_STATIC_IPS:
  INTERNAL_ONLY_DOMAINS:
  TRUSTED_DOMAIN_CIDRS:
  ROUTER_STATIC_IPS:
  DISABLE_INSECURE_COOKIES:
  ENABLE_ZIPKIN:
  ENABLE_WRITE_ACCESS_LOGS:
  REQUEST_TIMEOUT_IN_SECONDS:
  EXTRA_HEADERS_TO_LOG:
  DRAIN_WAIT:
  LB_HEALTHY_THRESHOLD:
  EXECUTOR_DISK_CAPACITY:
  EXECUTOR_MEMORY_CAPACITY:
  INSECURE_DOCKER_REGISTRY_LIST:
  PLACEMENT_TAG:
  ISOLATED_HA_PROXY_INSTANCES:
  ISOLATED_ROUTER_INSTANCES:
  ISOLATED_DIEGO_CELL_INSTANCES:

inputs:
  - name: pipelines-repo
  - name: pivnet-product


run:
  path: pipelines-repo/tasks/config-p-isolation-segment/task.sh
