pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
github_token: ((github_token)) # [R] Your github token
github_repo: https://github.com/BrianRagazzi/concourse-pipelines # [R] Pipelines github repo
github_branch: master

iaas_type: vsphere

debug: false # Set to true if you want to see all the tasks output. This will also show all the secrets and certs, so think twice

#opsman_major_minor_version: ^2\.1\..*$   # PCF Ops Manager minor version to track
pks_major_minor_version: ^1\.0\..*$    #PKS version to track
harbor_major_minor_version: ^1\.4\..*$ #Harbor verion to track

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr)) # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd)) # [R] Ops Manager admin password
