resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pipelines-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))

- name: pcf-ops-manager
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: elastic-runtime
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

- name: nsx-t-add-on-tile
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: vmware-nsx-t
    product_version: {{nsxt_major_minor_version}}
    sort_by: semver

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit


groups:
- name: om-ncp-pas
  jobs:
  - deploy-opsman
  - configure-director
  - deploy-director
  - upload-nsx
  - configure-nsx
  - upload-ert
  - configure-ert
  - deploy-ert
- name: post-deploy
  jobs:
  - pas-admin-user
- name: cleanup
  jobs:
  - wipe-env


jobs:
- name: deploy-opsman
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-opsman-product
      resource: pcf-ops-manager
      params: {globs: ["*.ova"]}
      trigger: true

  - task: deploy
    file: pipelines-repo/tasks/import-opsman/task.yml
    params:
      GOVC_INSECURE: {{vcenter_insecure}}
      GOVC_CA_CERT: {{vcenter_ca_cert}}
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_HOST: {{om_vm_host}}
      OPS_MGR_HOST: {{ops_mgr_host}}
      OM_VM_FOLDER: {{om_vm_folder}}
      OPS_MGR_SSH_PWD: {{om_ssh_pwd}}
      OM_NTP_SERVERS: {{om_ntp_servers}}
      OM_DNS_SERVERS: {{om_dns_servers}}
      OM_GATEWAY: {{om_gateway}}
      OM_NETMASK: {{om_netmask}}
      OM_IP: {{om_ip}}
      OM_VM_NETWORK: {{om_vm_network}}
      OM_VM_NAME: {{om_vm_name}}
      OM_RESOURCE_POOL: {{om_resource_pool}}
      OPSMAN_DISK_TYPE: {{opsman_disk_type}}
      OM_VM_POWER_STATE: {{om_vm_power_state}}

- name: configure-director
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-opsman]
      trigger: true

  - task: config-opsman-auth
    file: pipelines-repo/tasks/config-opsman/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OM_DECRYPTION_PWD: {{om_decryption_pwd}}

  - task: configure-director
    file: pipelines-repo/tasks/config-opsdir-pas-nsxt/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      VCENTER_HOST: {{vcenter_host}}
      VCENTER_USR: {{vcenter_usr}}
      VCENTER_PWD: {{vcenter_pwd}}
      VCENTER_DATA_CENTER: {{vcenter_data_center}}
      VCENTER_DISK_TYPE: {{vm_disk_type}}
      EPHEMERAL_STORAGE_NAMES: {{ephemeral_storage_names}}
      PERSISTENT_STORAGE_NAMES: {{persistent_storage_names}}
      BOSH_VM_FOLDER:  {{bosh_vm_folder}}
      BOSH_TEMPLATE_FOLDER: {{bosh_template_folder}}
      BOSH_DISK_PATH: {{bosh_disk_path}}
      NSX_NETWORKING_ENABLED: {{nsx_networking_enabled}}
      NSX_MODE: {{nsx_mode}}
      NSX_ADDRESS: {{nsx_address}}
      NSX_USERNAME: {{nsx_username}}
      NSX_PASSWORD: {{nsx_password}}
      NSX_CA_CERTIFICATE: {{nsx_ca_certificate}}
      SSL_VERIFICATION_ENABLED: {{ssl_verification_enabled}}
      NTP_SERVERS: {{ntp_servers}}
      ENABLE_VM_RESURRECTOR: {{enable_vm_resurrector}}
      METRICS_IP: {{metrics_ip}}
      OPENTSDB_IP: {{opentsdb_ip}}
      POST_DEPLOY_ENABLED: {{post_deploy_enabled}}
      BOSH_RECREATE_ON_NEXT_DEPLOY: {{bosh_recreate_on_next_deploy}}
      RETRY_BOSH_DEPLOYS: {{retry_bosh_deploys}}
      KEEP_UNREACHABLE_VMS: {{keep_unreachable_vms}}
      MAX_THREADS: {{max_threads}}
      DIRECTOR_WORKER_COUNT: {{director_worker_count}}
      OPS_DIR_HOSTNAME: {{ops_dir_hostname}}
      PAGER_DUTY_ENABLED: {{pager_duty_enabled}}
      PAGER_DUTY_SERVICE_KEY: {{pager_duty_service_key}}
      PAGER_DUTY_HTTP_PROXY: {{pager_duty_http_proxy}}
      HM_EMAIL_ENABLED: {{hm_email_enabled}}
      SMTP_HOST: {{smtp_host}}
      SMTP_PORT: {{smtp_port}}
      SMTP_DOMAIN: {{smtp_domain}}
      FROM_ADDRESS: {{from_address}}
      RECIPIENTS_ADDRESS: {{recipients_address}}
      SMTP_USER: {{smtp_user}}
      SMTP_PASSWORD: {{smtp_password}}
      SMTP_TLS_ENABLED: {{smtp_tls_enabled}}
      BLOBSTORE_TYPE: {{blobstore_type}}
      DATABASE_TYPE: {{database_type}}
      EXTERNAL_MYSQL_DB_HOST: {{external_mysql_db_host}}
      EXTERNAL_MYSQL_DB_PORT: {{external_mysql_db_port}}
      EXTERNAL_MYSQL_DB_USER: {{external_mysql_db_user}}
      EXTERNAL_MYSQL_DB_PASSWORD: {{external_mysql_db_password}}
      EXTERNAL_MYSQL_DB_DATABASE: {{external_mysql_db_database}}
      SYSLOG_ENABLED: {{syslog_enabled}}
      SYSLOG_ADDRESS: {{syslog_address}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_TRANSPORT_PROTOCOL: {{syslog_transport_protocol}}
      SYSLOG_TLS_ENABLED: {{syslog_tls_enabled}}
      SYSLOG_PERMITTED_PEER: {{syslog_permitted_peer}}
      SYSLOG_SSL_CA_CERTIFICATE: {{syslog_ssl_ca_certificate}}
      ICMP_CHECKS_ENABLED: {{icmp_checks_enabled}}
      INFRA_NETWORK_NAME: {{infra_network_name}}
      INFRA_VCENTER_NETWORK: {{infra_vsphere_network}}
      INFRA_NW_CIDR: {{infra_nw_cidr}}
      INFRA_EXCLUDED_RANGE: {{infra_excluded_range}}
      INFRA_NW_DNS: {{infra_nw_dns}}
      INFRA_NW_GATEWAY: {{infra_nw_gateway}}
      INFRA_NW_AZS: {{infra_nw_azs}}
      DEPLOYMENT_NETWORK_NAME: {{deployment_network_name}}
      DEPLOYMENT_VCENTER_NETWORK: {{deployment_vsphere_network}}
      DEPLOYMENT_NW_CIDR: {{deployment_nw_cidr}}
      DEPLOYMENT_EXCLUDED_RANGE: {{deployment_excluded_range}}
      DEPLOYMENT_NW_DNS: {{deployment_nw_dns}}
      DEPLOYMENT_NW_GATEWAY: {{deployment_nw_gateway}}
      DEPLOYMENT_NW_AZS: {{deployment_nw_azs}}
      SERVICES_NETWORK_NAME: {{services_network_name}}
      SERVICES_VCENTER_NETWORK: {{services_vsphere_network}}
      SERVICES_NW_CIDR: {{services_nw_cidr}}
      SERVICES_EXCLUDED_RANGE: {{services_excluded_range}}
      SERVICES_NW_DNS: {{services_nw_dns}}
      SERVICES_NW_GATEWAY: {{services_nw_gateway}}
      SERVICES_NW_AZS: {{services_nw_azs}}
      DYNAMIC_SERVICES_NETWORK_NAME: {{dynamic_services_network_name}}
      DYNAMIC_SERVICES_VCENTER_NETWORK: {{dynamic_services_vsphere_network}}
      DYNAMIC_SERVICES_NW_CIDR: {{dynamic_services_nw_cidr}}
      DYNAMIC_SERVICES_EXCLUDED_RANGE: {{dynamic_services_excluded_range}}
      DYNAMIC_SERVICES_NW_DNS: {{dynamic_services_nw_dns}}
      DYNAMIC_SERVICES_NW_GATEWAY: {{dynamic_services_nw_gateway}}
      DYNAMIC_SERVICES_NW_AZS: {{dynamic_services_nw_azs}}
      AZ_1: {{az_1_name}}
      AZ_1_CLUSTER_NAME: {{az_1_cluster_name}}
      AZ_1_RP_NAME: {{az_1_rp_name}}
      AZ_2: {{az_2_name}}
      AZ_2_CLUSTER_NAME: {{az_2_cluster_name}}
      AZ_2_RP_NAME: {{az_2_rp_name}}
      AZ_3: {{az_3_name}}
      AZ_3_CLUSTER_NAME: {{az_3_cluster_name}}
      AZ_3_RP_NAME: {{az_3_rp_name}}
      TRUSTED_CERTIFICATES: {{trusted_certificates}}
      GENERATE_VM_PASSWORDS: {{generate_vm_passwords}}

- name: deploy-director
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-director]
      trigger: true

  - task: apply-changes
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: upload-ert
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: elastic-runtime
      params: {globs: ["cf*.pivotal"]}
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-director]
      trigger: true
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-ert-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

  - task: upload-stemcell
    file: pipelines-repo/tasks/stemcell-uploader/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))
      IAAS_TYPE: ((iaas_type))

- name: configure-ert
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [upload-ert]
      trigger: true

  - task: configure-ert
    file: pipelines-repo/tasks/config-ert-2.2/task.yml
    params:
      IAAS: vsphere
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      ERT_SINGLETON_JOB_AZ: {{ert_singleton_job_az}}
      DEPLOYMENT_NW_AZS: {{deployment_nw_azs}}
      NETWORK_NAME: {{deployment_network_name}}
      ENABLE_SECURITY_EVENT_LOGGING: {{enable_security_event_logging}}
      SYSLOG_HOST: {{syslog_address}}
      SYSLOG_PORT: {{syslog_port}}
      SYSLOG_PROTOCOL: {{syslog_transport_protocol}}
      SYSLOG_DRAIN_BUFFER_SIZE: {{syslog_drain_buffer_size}}
      COMPANY_NAME: {{company_name}}
      AUTHENTICATION_MODE: {{authentication_mode}}
      LOGGREGATOR_ENDPOINT_PORT: {{loggregator_endpoint_port}}
      SSL_CERT: {{ssl_cert}}
      SSL_PRIVATE_KEY: {{ssl_private_key}}
      SAML_SSL_CERT: {{saml_ssl_cert}}
      SAML_SSL_PRIVATE_KEY: {{saml_ssl_private_key}}
      HAPROXY_FORWARD_TLS: {{haproxy_forward_tls}}
      HAPROXY_BACKEND_CA: {{haproxy_backend_ca}}
      ROUTER_TLS_CIPHERS: {{router_tls_ciphers}}
      HAPROXY_TLS_CIPHERS: {{haproxy_tls_ciphers}}
      DISABLE_HTTP_PROXY: {{disable_http_proxy}}
      TCP_ROUTING: {{tcp_routing}}
      TCP_ROUTING_PORTS: {{tcp_routing_ports}}
      ROUTE_SERVICES: {{route_services}}
      IGNORE_SSL_CERT: {{ignore_ssl_cert_verification}}
      SMTP_FROM: {{smtp_from}}
      SMTP_ADDRESS: {{smtp_address}}
      SMTP_PORT: {{smtp_port}}
      SMTP_USER: {{smtp_user}}
      SMTP_PWD: {{smtp_pwd}}
      SMTP_AUTH_MECHANISM: {{smtp_auth_mechanism}}
      LDAP_URL: {{ldap_url}}
      LDAP_USER: {{ldap_user}}
      LDAP_PWD: {{ldap_pwd}}
      SEARCH_BASE: {{search_base}}
      SEARCH_FILTER: {{search_filter}}
      GROUP_SEARCH_BASE: {{group_search_base}}
      GROUP_SEARCH_FILTER: {{group_search_filter}}
      MAIL_ATTR_NAME: {{mail_attribute_name}}
      FIRST_NAME_ATTR: {{first_name_attribute}}
      LAST_NAME_ATTR: {{last_name_attribute}}
      SECURITY_ACKNOWLEDGEMENT: {{security_acknowledgement}}
      SYSTEM_DOMAIN: {{system_domain}}
      APPS_DOMAIN: {{apps_domain}}
      DEFAULT_QUOTA_MEMORY_LIMIT_IN_MB: {{default_quota_memory_limit_mb}}
      DEFAULT_QUOTA_MAX_SERVICES_COUNT: {{default_quota_max_number_services}}
      HA_PROXY_IPS: {{ha_proxy_ips}}
      SKIP_CERT_VERIFY: {{skip_cert_verify}}
      DISABLE_INSECURE_COOKIES: {{disable_insecure_cookies}}
      ROUTER_STATIC_IPS: {{router_static_ips}}
      MYSQL_PROXY_STATIC_IPS: {{mysql_proxy_static_ips}}
      MYSQL_PROXY_SERVICE_HOSTNAME: {{mysql_proxy_service_hostname}}
      MYSQL_PROXY_STARTUP_DELAY: {{mysql_proxy_startup_delay}}
      MYSQL_PROXY_SHUTDOWN_DELAY: {{mysql_proxy_shutdown_delay}}
      ROUTER_REQUEST_TIMEOUT_IN_SEC: {{router_request_timeout_in_seconds}}
      GARDEN_NETWORK_POOL_CIDR: {{garden_network_pool_cidr}}
      GARDEN_NETWORK_MTU: {{garden_network_mtu}}
      MYSQL_MONITOR_EMAIL: {{mysql_monitor_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      ALLOW_APP_SSH_ACCESS: {{allow_app_ssh_access}}
      TCP_ROUTER_STATIC_IPS: {{tcp_router_static_ips}}
      SSH_STATIC_IPS: {{ssh_static_ips}}
      CONSUL_SERVER_INSTANCES: {{consul_server_instances}}
      NATS_INSTANCES: {{nats_instances}}
      NFS_SERVER_INSTANCES: {{nfs_server_instances}}
      MYSQL_PROXY_INSTANCES: {{mysql_proxy_instances}}
      MYSQL_INSTANCES: {{mysql_instances}}
      BACKUP_PREPARE_INSTANCES: {{backup_prepare_instances}}
      UAA_INSTANCES: {{uaa_instances}}
      CLOUD_CONTROLLER_INSTANCES: {{cloud_controller_instances}}
      HA_PROXY_INSTANCES: {{ha_proxy_instances}}
      ROUTER_INSTANCES: {{router_instances}}
      MYSQL_MONITOR_INSTANCES: {{mysql_monitor_instances}}
      CLOCK_GLOBAL_INSTANCES: {{clock_global_instances}}
      CLOUD_CONTROLLER_WORKER_INSTANCES: {{cloud_controller_worker_instances}}
      DIEGO_DATABASE_INSTANCES: {{diego_database_instances}}
      DIEGO_BRAIN_INSTANCES: {{diego_brain_instances}}
      DIEGO_CELL_INSTANCES: {{diego_cell_instances}}
      DOPPLER_INSTANCES: {{doppler_instances}}
      LOGGREGATOR_TC_INSTANCES: {{loggregator_traffic_controller_instances}}
      TCP_ROUTER_INSTANCES: {{tcp_router_instances}}
      SYSLOG_ADAPTER_INSTANCES: {{syslog_adapter_instances}}
      INTERNET_CONNECTED: {{internet_connected}}
      CONTAINER_NETWORKING_NW_CIDR: {{container_networking_nw_cidr}}
      TCP_ROUTER_NSX_SECURITY_GROUP: {{tcp_router_nsx_security_group}}
      TCP_ROUTER_NSX_LB_EDGE_NAME: {{tcp_router_nsx_lb_edge_name}}
      TCP_ROUTER_NSX_LB_POOL_NAME: {{tcp_router_nsx_lb_pool_name}}
      TCP_ROUTER_NSX_LB_SECURITY_GROUP: {{tcp_router_nsx_lb_security_group}}
      TCP_ROUTER_NSX_LB_PORT: {{tcp_router_nsx_lb_port}}
      ROUTER_NSX_SECURITY_GROUP: {{router_nsx_security_group}}
      ROUTER_NSX_LB_EDGE_NAME: {{router_nsx_lb_edge_name}}
      ROUTER_NSX_LB_POOL_NAME: {{router_nsx_lb_pool_name}}
      ROUTER_NSX_LB_SECURITY_GROUP: {{router_nsx_lb_security_group}}
      ROUTER_NSX_LB_PORT: {{router_nsx_lb_port}}
      DIEGO_BRAIN_NSX_SECURITY_GROUP: {{diego_brain_nsx_security_group}}
      DIEGO_BRAIN_NSX_LB_EDGE_NAME: {{diego_brain_nsx_lb_edge_name}}
      DIEGO_BRAIN_NSX_LB_POOL_NAME: {{diego_brain_nsx_lb_pool_name}}
      DIEGO_BRAIN_NSX_LB_SECURITY_GROUP: {{diego_brain_nsx_lb_security_group}}
      DIEGO_BRAIN_NSX_LB_PORT: {{diego_brain_nsx_lb_port}}
      HA_PROXY_LB_NAME: ""
      HAPROXY_FLOATING_IPS: ""
      CONTAINER_NETWORKING_INTERFACE_PLUGIN: {{container_networking_interface_plugin}}
      CREDHUB_PASSWORD: {{credhub_password}}
      BLOBSTORE_INTERNAL_ACCESS_SUBNET: {{blobstore_internal_access_subnet}}
      ENABLE_GROOTFS: {{enable_grootfs}}
      ROUTING_TLS_TERMINATION: {{routing_tls_termination}}
      ROUTER_CLIENT_CERT_VALIDATION: {{router_client_cert_validation}}
      ROUTING_CUSTOM_CA_CERTIFICATES: {{trusted_certificates}}

  - task: configure-errands
    file: pipelines-repo/tasks/config-errands/task.yml
    params:
      PRODUCT_NAME: cf
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      ERRANDS_TO_RUN_ON_CHANGE: {{ert_errands_to_run_on_change}}
      ERRANDS_TO_DISABLE: {{ert_errands_to_disable}}

- name: upload-nsx
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pivnet-product
      resource: nsx-t-add-on-tile
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [deploy-director]
      trigger: true
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"

  - task: upload-nsx-tile
    file: pipelines-repo/tasks/upload-product/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))
      PIVNET_API_TOKEN: ((pivnet_token))

  # - task: upload-stemcell
  #   file: pipelines-repo/tasks/stemcell-uploader/task.yml
  #   params:
  #     DEBUG: ((debug))
  #     OPS_MGR_HOST: ((ops_mgr_host))
  #     OPS_MGR_USR: ((ops_mgr_usr))
  #     OPS_MGR_PWD: ((ops_mgr_pwd))
  #     PIVNET_API_TOKEN: ((pivnet_token))
  #     IAAS_TYPE: ((iaas_type))

- name: configure-nsx
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [upload-nsx,configure-ert]
      trigger: true
    - get: pivnet-product
      resource: nsx-t-add-on-tile
      params: {globs: []}

  - task: configure-nsx
    file: pipelines-repo/tasks/config-nsx-t/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      NSX_API_MANAGERS: {{nsx_address}}
      NSX_API_USER: {{nsx_username}}
      NSX_API_PASSWORD: {{nsx_password}}
      NSX_API_CA_CERT:  #leave this empty as it's broken in NCP 2.1.2 and 2.1.3
      NSX_FOUNDATION_NAME: {{nsx_foundation_name}}
      NSX_NCP_DEBUG_LOG: {{nsx_ncp_debug_log}}
      NSX_SUBNET_PREFIX: {{nsx_subnet_prefix}}
      NSX_LOG_DROPPED_TRAFFIC: {{nsx_log_dropped_traffic}}
      NSX_ENABLE_SNAT: {{nsx_enable_snat}}
      NSX_EXTERNAL_SUBNET_PREFIX: {{nsx_external_subnet_prefix}}
      NSX_PRODUCT_TILE_NAME: {{nsx_product_tile_name}}
      NSX_AUTH_TYPE: {{nsx_auth_type}}
      NSX_CLIENT_CERT_CERT: {{nsx_client_cert_cert}}
      NSX_CLIENT_CERT_PRIVATE_KEY: {{nsx_client_cert_private_key}}
      OVERLAY_TZ: {{overlay_tz}}
      TIER0_ROUTER: {{tier0_router}}
      CONTAINER_IP_BLOCKS_NAME: {{container_ip_blocks_name}}
      EXTERNAL_IP_POOLS_NAME: {{external_ip_pools_name}}

- name: deploy-ert
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: pcf-ops-manager
      params: {globs: []}
      passed: [configure-ert, configure-nsx]
      trigger: true

  - task: deploy-ert
    file: pipelines-repo/tasks/apply-changes/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}

- name: pas-admin-user
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [deploy-ert]
      trigger: true

  - task: config-pas-admin-user
    file: pipelines-repo/tasks/config-pas-admin-user/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      PAS_ADMIN_USERNAME: {{pas_cli_username}}
      PAS_ADMIN_PASSWORD: {{pas_cli_password}}


- name: wipe-env
  plan:
  - aggregate:
    - get: pipelines-repo
  - task: wipe
    file: pipelines-repo/tasks/wipe-env/task.yml
    params:
      OPS_MGR_HOST: {{ops_mgr_host}}
      OPS_MGR_USR: {{ops_mgr_usr}}
      OPS_MGR_PWD: {{ops_mgr_pwd}}
      OPSMAN_IP: {{om_ip}}
      GOVC_INSECURE: {{vcenter_insecure}}
      GOVC_CA_CERT: {{vcenter_ca_cert}}
      GOVC_URL: {{vcenter_host}}
      GOVC_USERNAME: {{vcenter_usr}}
      GOVC_PASSWORD: {{vcenter_pwd}}
      GOVC_DATACENTER: {{vcenter_data_center}}
      GOVC_DATASTORE: {{om_data_store}}
      GOVC_NETWORK: {{om_vm_network}}
      GOVC_RESOURCE_POOL: {{om_resource_pool}}
      GOVC_HOST: {{om_vm_host}}
