resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
      tag: {{docker-tag}}

resources:
  - name: send-an-email
    type: email
    source:
      smtp:
        host: {{smtp-host}}
        port: {{smtp-port}}
        anonymous: true
        skip_ssl_validation: true
      from: {{email-from}}
      to: [ {{email-to}} ]

jobs:
  - name: send-email
    plan:
      - task: prep-email
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: concourse/buildroot
              tag: git
          params:
            OUTPUT_SUBJECT_FILE_NAME: generated-subject
            OUTPUT_BODY_FILE_NAME: generated-body
          run:
            path: sh
            args:
            - -exc
            - |
              # ensure you esape the ${BUILD_ID} variable with leading \
              echo -e "Email resource demo on $(date): build \${BUILD_ID}" > email-out/${OUTPUT_SUBJECT_FILE_NAME}
              echo -e "Cheers!\n\n \
              Build ID: \${BUILD_ID} \n \
              Build Name: \${BUILD_NAME} \n \
              Build Job Name: \${BUILD_JOB_NAME} \n \
              Build Pipeline Name: \${BUILD_PIPELINE_NAME} \n \
              ATC External URL: \${ATC_EXTERNAL_URL}" > email-out/${OUTPUT_BODY_FILE_NAME}
          outputs:
          - name: email-out
      - put: send-an-email
        params:
          subject: email-out/generated-subject
          body: email-out/generated-body
