---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/config-pas-admin-user/task.sh

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PAS_ADMIN_USERNAME:
  PAS_ADMIN_PASSWORD:
