resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

# - name: stemcell-trusty-pivnet
#   type: pivnet
#   source:
#     api_token: {{pivnet_token}}
#     product_slug: stemcells
#     sort_by: semver

- name: stemcell-pivnet-pas
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells-ubuntu-xenial
    product_version: {{pas_stemcell_major_minor_version}}
    sort_by: semver

- name: stemcell-pivnet-hw
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: stemcells-ubuntu-xenial
    product_version: {{healthwatch_stemcell_major_minor_version}}
    sort_by: semver

- name: ops-manager-pivnet
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: elastic-runtime-pivnet
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

- name: pcf-healthwatch-pivnet
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: p-healthwatch
    product_version: {{healthwatch_major_minor_version}}
    sort_by: semver

- name: nsxt-pivnet
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: vmware-nsx-t
    product_version: {{nsxt_major_minor_version}}
    sort_by: semver

# - name: iso-seg-pivnet
#   type: pivnet
#   source:
#     api_token: {{pivnet_token}}
#     product_slug: p-isolation-segment
#     sort_by: semver
#
# - name: mysql-pivnet
#   type: pivnet
#   source:
#     api_token: {{pivnet_token}}
#     product_slug: p-mysql
#     sort_by: semver
#
# - name: redis-pivnet
#   type: pivnet
#   source:
#     api_token: {{pivnet_token}}
#     product_slug: p-redis
#     sort_by: semver

# - name: pcfnorm-rootfs
#   type: docker-image
#   source:
#     repository: pcfnorm/rootfs
#     tag: latest
#     username: {{dockerhub_username}}
#     password: {{dockerhub_password}}

- name: ops-manager-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/ops-manager/pcf-vsphere-(.*).ova"
    disable_ssl: false
    skip_ssl_verification: true

- name: pivotal-app-services-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/PAS/cf-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true

- name: small-footprint-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/PAS/srt-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true

- name: pcf-healthwatch-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/Tiles/p-healthwatch-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true
#
# - name: iso-seg-s3
#   type: s3
#   source:
#     access_key_id: {{s3_access_key_id}}
#     secret_access_key: {{s3_secret_access_key}}
#     endpoint: {{s3_endpoint}}
#     bucket: {{s3_bucket}}
#     regexp: "PCF/Tiles/p-isolation-segment-(.*).pivotal"
#     disable_ssl: false
#     skip_ssl_verification: true
#
# - name: mysql-s3
#   type: s3
#   source:
#     access_key_id: {{s3_access_key_id}}
#     secret_access_key: {{s3_secret_access_key}}
#     endpoint: {{s3_endpoint}}
#     bucket: {{s3_bucket}}
#     regexp: "PCF/Tiles/p-mysql-(.*).pivotal"
#     disable_ssl: false
#     skip_ssl_verification: true
#
# - name: redis-s3
#   type: s3
#   source:
#     access_key_id: {{s3_access_key_id}}
#     secret_access_key: {{s3_secret_access_key}}
#     endpoint: {{s3_endpoint}}
#     bucket: {{s3_bucket}}
#     regexp: "PCF/Tiles/p-redis-(.*).pivotal"
#     disable_ssl: false
#     skip_ssl_verification: true



- name: stemcell-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    disable_ssl: false
    regexp: PCF/stemcells/bosh-stemcell-(.*)-.*.tgz
    skip_ssl_verification: true

- name: nsxt-s3
  type: s3
  source:
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    regexp: "PCF/Tiles/VMware-NSX-T-(.*).pivotal"
    disable_ssl: false
    skip_ssl_verification: true


jobs:
# - name: stemcell-trusty
#   plan:
#   - get: stemcell-trusty-pivnet
#     trigger: true
#     params:
#       globs: ["*vsphere-esxi-ubuntu-trusty-go_agent*"]
#   - put: stemcell-s3
#     params:
#       file: "stemcell-trusty-pivnet/*.tgz"

- name: stemcell-xenial-pas
  plan:
  - get: stemcell-pivnet-pas
    trigger: true
    params:
      globs: ["*vsphere-esxi-ubuntu-xenial-go_agent*"]
  - put: stemcell-s3
    params:
      file: "stemcell-pivnet-pas/*.tgz"

- name: stemcell-xenial-healthwatch
  plan:
  - get: stemcell-pivnet-hw
    trigger: true
    params:
      globs: ["*vsphere-esxi-ubuntu-xenial-go_agent*"]
  - put: stemcell-s3
    params:
      file: "stemcell-pivnet-hw/*.tgz"

- name: ops-manager
  plan:
  - get: ops-manager-pivnet
    params:
      globs: ["*.ova"]
  - put: ops-manager-s3
    params:
      file: "ops-manager-pivnet/pcf-vsphere-*.ova"


- name: small-footprint-pas
  build_logs_to_retain: 2
  plan:
  - get: elastic-runtime-pivnet
    params:
      globs: ["srt-*.pivotal"]
  - put: small-footprint-s3
    params:
      file: "elastic-runtime-pivnet/srt-*.pivotal"

- name: elastic-runtime
  build_logs_to_retain: 2
  plan:
  - get: elastic-runtime-pivnet
    params:
      globs: ["cf-*.pivotal"]
  - put: pivotal-app-services-s3
    params:
      file: "elastic-runtime-pivnet/cf-*.pivotal"

- name: nsxt
  plan:
  - get: nsxt-pivnet
    trigger: true
    params:
      globs: ["*.pivotal"]
  - put: nsxt-s3
    params:
      file: "nsxt-pivnet/VMware-NSX-T-*.pivotal"

- name: pcf-healthwatch
  plan:
  - get: pcf-healthwatch-pivnet
    params:
      globs: ["*.pivotal"]
  - put: pcf-healthwatch-s3
    params:
      file: "pcf-healthwatch-pivnet/p-healthwatch-*.pivotal"
