---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


params:
  GOVC_INSECURE:
  GOVC_CA_CERT:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:
  OPS_MGR_HOST:
  OPS_MGR_SSH_PWD:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OM_RESOURCE_POOL:
  OPSMAN_DISK_TYPE:
  OM_VM_POWER_STATE:
  OM_VM_FOLDER:


inputs:
  - name: pivnet-opsman-product
  - name: pipelines-repo

run:
  path: pipelines-repo/tasks/import-opsman/task.sh
