---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
  - name: pipelines-repo

params:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OPS_MGR_HOST:

run:
  path: pipelines-repo/tasks/wait-opsman-clear/task.sh
