---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pipelines-repo

run:
  path: pipelines-repo/tasks/create-pks-cluster/task.sh

params:
  PCF_PKS_API:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
  PKS_SERVICE_PLAN_NAME:
  PKS_CLUSTER_NAME:
  PKS_CLUSTER_NUMBER_OF_WORKERS:
  NSX_MANAGER_USERNAME:
  NSX_MANAGER_PASSWORD:
  NSX_MANAGER_IP:
  PKS_KEEP_FAILED_CLUSTER_ALIVE:
  UAA_URL:
