---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pipelines-repo

run:
  path: pipelines-repo/tasks/report-pks-clusters/task.sh

params:
  UAA_URL:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
